### ISSUE TITLE
You can include C files in build system directly

### ISSUE THREAD

**Issue by RUSshy** [danielabbott/Game-Engine#1]
Just like this:

```zig
    exe.addCSourceFile("../libs/glad/src/glad.c", &[_][]const u8{"-std=c99"});
    exe.addCSourceFile("../libs/stb/src/stb.c", &[_][]const u8{"-std=c99"});
```

It'll automatically build and link the lib

**Comment by danielabbott** [comment]
I don't have the development environment set up to make the changes but yes that is a better way of doing it.

**Comment by RUSshy** [comment]
you don't use ZIG anymore? i'm curious to know why? if you don't mind sharing your experience (i picked up the language few weeks ago only)

**Comment by danielabbott** [comment]
Using C libraries from Zig was a pain because Zig's C parser would come across bits of code in the header files that it didn't understand so I switched back to C++. Sorry for the late reply :p

**Comment by RUSshy** [comment]
Oh i see, i personally switched back to D, zig is way too verbose and limiting
